### ISSUE TITLE
Can't progress to tutorial

### ISSUE THREAD

**Issue by DiamondWolf3393** [Monika-After-Story/DDLCModTemplate#40]
As soon as Monika tries to speak, it crashes. Here's the traceback:

While running game code:
  File "game/script.rpy", line 29, in script call
    call example_chapter from _call_example_chapter
  File "game/tutorials.rpy", line 98, in script
    call screen tutorial_choice(items)
  File "renpy/common/000statements.rpy", line 531, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
AttributeError: 'NoneType' object has no attribute 'append'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 29, in script call
    call example_chapter from _call_example_chapter
  File "game/tutorials.rpy", line 98, in script
    call screen tutorial_choice(items)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 1947, in execute
    self.call("execute")
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\ast.py", line 1935, in call
    return renpy.statements.call(method, parsed, *args, **kwargs)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\statements.py", line 277, in call
    return method(parsed, *args, **kwargs)
  File "renpy/common/000statements.rpy", line 531, in execute_call_screen
    store._return = renpy.call_screen(name, *args, **kwargs)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\exports.py", line 2896, in call_screen
    rv = renpy.ui.interact(mouse="screen", type="screen", roll_forward=roll_forward)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\ui.py", line 295, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\core.py", line 2699, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, **kwargs)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\core.py", line 3191, in interact_core
    self.draw_screen(root_widget, fullscreen_video, (not fullscreen_video) or video_frame_drawn)
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\core.py", line 2091, in draw_screen
    renpy.config.screen_height,
  File "render.pyx", line 546, in renpy.display.render.render_screen
  File "render.pyx", line 247, in renpy.display.render.render
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 154, in renpy.display.render.render
  File "render.pyx", line 247, in renpy.display.render.render
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 154, in renpy.display.render.render
  File "render.pyx", line 247, in renpy.display.render.render
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 154, in renpy.display.render.render
  File "render.pyx", line 247, in renpy.display.render.render
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\screen.py", line 675, in render
    child = renpy.display.render.render(self.child, w, h, st, at)
  File "render.pyx", line 154, in renpy.display.render.render
  File "render.pyx", line 247, in renpy.display.render.render
  File "C:\Users\BendyBoi\Downloads\renpy-7.3.2-sdk\renpy\display\layout.py", line 722, in render
    surf = render(child, width, height, cst, cat)
  File "render.pyx", line 154, in renpy.display.render.render
  File "render.pyx", line 256, in renpy.display.render.render
AttributeError: 'NoneType' object has no attribute 'append'

**Comment by ZhugeSong** [comment]
From the paths you have in the traceback, it looks like you are using Ren'Py version 7.3.2. DDLC and this template works with version 6.99.12, so try downloading that (link in the README) and giving it another go.
